//
//  APIClient.swift
//  nearby
//
//  Created by Max Myron on 9/4/26.
//

import Foundation

protocol APIClientProtocol {
    // fetches landmarks from API
    func fetchLandmarks(geohash: String) async throws -> [LandmarkDTO]
    
    // turns onboarding vibe input into a series of preferences.
    func fetchPreferences(from sentence: String) async throws -> [LandmarkPreferenceDTO]
}

class APIClient: APIClientProtocol {
    private let llmClient: LLMClientProtocol
    
    init(llmClient: LLMClientProtocol) {
        self.llmClient = llmClient
    }
    
    func fetchLandmarks(geohash: String) async throws -> [LandmarkDTO] {
        guard let location = Geohash.decode(hash: geohash) else {
            return []
        }
        
        // AI-generated by Google Gemini 3.1 Pro on 22 Aug 2026
        let sparqlQuery = """
        SELECT ?item ?itemLabel ?lat ?lon ?sitelink WHERE {
          BIND("Point(\(location.longitude) \(location.latitude))"^^geo:wktLiteral AS ?centerLocation)
          SERVICE wikibase:around {
            ?item wdt:P625 ?coordinate .
            bd:serviceParam wikibase:center ?centerLocation .
            bd:serviceParam wikibase:radius "1" . # Radius in kilometers
          }
          ?item p:P625/psv:P625 ?coordinateNode .
          ?coordinateNode wikibase:geoLatitude ?lat ;
                          wikibase:geoLongitude ?lon .
          MINUS {
            ?item wdt:P31/wdt:P279* ?unwantedClass .
            VALUES ?unwantedClass { wd:Q486972 wd:Q56061 wd:Q34442 wd:Q37299 wd:Q13406463 wd:Q4167410 }
          }
          ?sitelink schema:about ?item ;
                    schema:isPartOf <https://en.wikipedia.org/> .
          SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
        }
        LIMIT 5
        """
        
        var components = URLComponents(string: "https://query.wikidata.org/sparql")!
        components.queryItems = [URLQueryItem(name: "query", value: sparqlQuery)]
            
        guard let url = components.url else {
            print("Error: Could not construct URL")
            return []
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("application/sparql-results+json", forHTTPHeaderField: "Accept")
        request.setValue("landmarks/1.0 (mailto:max@mmyron.com)", forHTTPHeaderField: "User-Agent")
        
        let (data, response) = try await URLSession.shared.data(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            let msg = "HTTP Request Failed. Status code: \((response as? HTTPURLResponse)?.statusCode ?? 0)".data(using: .utf8) ?? Data()
            FileHandle.standardError.write(msg)
            return []
        }
        
        print("Successful 2XX response from Wikipedia!")
        
        do {
            let decoded = try JSONDecoder().decode(SPARQLResponse.self, from: data)
            print("successful decoding")
            print("\(decoded.results.bindings)")
            return decoded.results.bindings.map { LandmarkDTO(from: $0) }
        } catch {
            let msg = "JSONDecoder().decode failed; could not decode httpResponse to type SparQLResponse.self: \(error.localizedDescription)".data(using: .utf8) ?? Data()
            print(msg)
            FileHandle.standardError.write(msg)
            return []
        }
    }
    
    func fetchPreferences(from sentence: String) async throws -> [LandmarkPreferenceDTO] {
        return try await llmClient.determinePreferences(from: sentence)
    }
}

struct LandmarkDTO: Codable {
    var wikidataID: String
    var name: String
    var summary: String
    
    var latitude: Double
    var longitude: Double

    var vibes: [String] = []
    var classifications: [String] = []
    
    init(from response: WikipediaFetchSPARQLResponse) {
        self.wikidataID = response.item.value
        self.name = response.itemLabel.value
        self.summary = ""
        self.latitude = response.lat.value
        self.longitude = response.lon.value
    }
}

struct LandmarkPreferenceDTO: Codable {
    var type: LandmarkPreference.PreferenceType
    var value: String
}

// Mark: Wikipedia client responses (delete these in the future)

struct SPARQLResponse: Decodable {
    let results: SPARQLResults
}

struct SPARQLResults: Decodable {
    let bindings: [WikipediaFetchSPARQLResponse]
}

struct WikipediaFetchSPARQLResponse: Decodable {
    let item: SPARQLStringValue
    let itemLabel: SPARQLStringValue
    let lat: SPARQLDoubleValue
    let lon: SPARQLDoubleValue
    let sitelink: SPARQLStringValue
}

struct SPARQLStringValue: Decodable {
    let value: String
    
    init(_ value: String) {
        self.value = value
    }
}

struct SPARQLDoubleValue: Decodable {
    let value: Double
    
    init (_ value: Double) {
        self.value = value
    }
    
    enum CodingKeys: String, CodingKey {
        case value
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        // 1. Decode the Wikidata value as a String
        let stringValue = try container.decode(String.self, forKey: .value)
        
        // 2. Convert it to a Double
        if let doubleValue = Double(stringValue) {
            self.value = doubleValue
        } else {
            throw DecodingError.dataCorruptedError(
                forKey: .value,
                in: container,
                debugDescription: "Could not convert Wikidata string to Double."
            )
        }
    }
}
