//
//  WikipediaClient.swift
//  nearby
//
//  Created by Max Myron on 5/1/26.
//

import Foundation
import SwiftData
import MapKit

protocol WikipediaClientProtocol {
    func fetchLandmarks(at location: CLLocationCoordinate2D) async throws -> [WikipediaFetchSPARQLResponse]
}

@MainActor
class WikipediaClient: WikipediaClientProtocol {
    let unwantedClasses = [
        "wd:Q486972",   // Human settlement (Cities, towns, villages, neighborhoods)
        "wd:Q56061",    // Administrative territorial entity (States, counties, districts)
        "wd:Q34442",    // Road / Street (Coordinate points for long roads are usually unhelpful)
        "wd:Q37299",    // Bus stop (Clutters maps with uninteresting transit points)
        "wd:Q13406463", // Wikimedia list article (e.g., "List of monuments in Paris")
        "wd:Q4167410",  // Wikimedia disambiguation page
    ]
    
    func fetchLandmarks(at location: CLLocationCoordinate2D) async throws -> [WikipediaFetchSPARQLResponse] {
        print("Fetching landmarks at (\(location.latitude), \(location.longitude))")
        // AI-generated by Google Gemini 3.1 Pro on 22 Aug 2026
        let sparqlQuery = """
        SELECT ?item ?itemLabel ?lat ?lon ?sitelink WHERE {
          BIND("Point(\(location.longitude) \(location.latitude))"^^geo:wktLiteral AS ?centerLocation)
          SERVICE wikibase:around {
            ?item wdt:P625 ?coordinate .
            bd:serviceParam wikibase:center ?centerLocation .
            bd:serviceParam wikibase:radius "1" . # Radius in kilometers
          }
          ?item p:P625/psv:P625 ?coordinateNode .
          ?coordinateNode wikibase:geoLatitude ?lat ;
                          wikibase:geoLongitude ?lon .
          MINUS {
            ?item wdt:P31/wdt:P279* ?unwantedClass .
            VALUES ?unwantedClass { \(unwantedClasses.joined(separator: " ")) }
          }
          ?sitelink schema:about ?item ;
                    schema:isPartOf <https://en.wikipedia.org/> .
          SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
        }
        LIMIT 5
        """
        
        var components = URLComponents(string: "https://query.wikidata.org/sparql")!
        components.queryItems = [URLQueryItem(name: "query", value: sparqlQuery)]
            
        guard let url = components.url else {
            print("Error: Could not construct URL")
            return []
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("application/sparql-results+json", forHTTPHeaderField: "Accept")
        request.setValue("landmarks/1.0 (mailto:max@mmyron.com)", forHTTPHeaderField: "User-Agent")
        
        let (data, response) = try await URLSession.shared.data(for: request)
        
        guard let httpResponse = response as? HTTPURLResponse,
              (200...299).contains(httpResponse.statusCode) else {
            let msg = "HTTP Request Failed. Status code: \((response as? HTTPURLResponse)?.statusCode ?? 0)".data(using: .utf8) ?? Data()
            FileHandle.standardError.write(msg)
            return []
        }
        
        print("Successful 2XX response from Wikipedia!")
        
        do {
            let decoded = try JSONDecoder().decode(SPARQLResponse.self, from: data)
            print("successful decoding")
            print("\(decoded.results.bindings)")
            return decoded.results.bindings
        } catch {
            let msg = "JSONDecoder().decode failed; could not decode httpResponse to type SparQLResponse.self: \(error.localizedDescription)".data(using: .utf8) ?? Data()
            print(msg)
            FileHandle.standardError.write(msg)
            return []
        }
    }
}

// 2. Define Data Models for JSON Decoding
struct SPARQLResponse: Decodable {
    let results: SPARQLResults
}

struct SPARQLResults: Decodable {
    let bindings: [WikipediaFetchSPARQLResponse]
}

struct WikipediaFetchSPARQLResponse: Decodable {
    let item: SPARQLStringValue
    let itemLabel: SPARQLStringValue
    let lat: SPARQLDoubleValue
    let lon: SPARQLDoubleValue
    let sitelink: SPARQLStringValue
}

struct SPARQLStringValue: Decodable {
    let value: String
    
    init(_ value: String) {
        self.value = value
    }
}

struct SPARQLDoubleValue: Decodable {
    let value: Double
    
    init (_ value: Double) {
        self.value = value
    }
    
    enum CodingKeys: String, CodingKey {
        case value
    }
    
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        // 1. Decode the Wikidata value as a String
        let stringValue = try container.decode(String.self, forKey: .value)
        
        // 2. Convert it to a Double
        if let doubleValue = Double(stringValue) {
            self.value = doubleValue
        } else {
            throw DecodingError.dataCorruptedError(
                forKey: .value,
                in: container,
                debugDescription: "Could not convert Wikidata string to Double."
            )
        }
    }
}
